In [1]:
import numpy as np

# Numpy 

## Arrays

Los arreglos de NumPy son creados llamando al método array() de la biblioteca de NumPy. Cómo argumento del método, se debe pasar una lista.

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Hay diferentes tipos de arreglos en diferentes dimensiones. Pueden ser de una dimension (vectores), dos dimensiones (matrices), o n-dimensionales

In [3]:
# Uni-dimensional (vectores)
uni_dimensional = np.array([1,2,3])
print(uni_dimensional.shape)

# dos-dimensional (matrices)
dos_dimensional = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(dos_dimensional.shape)

# tri-dimensional (tensores de orden 3)
tres_dimensional = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(tres_dimensional.shape)

(3,)
(3, 3)
(3, 2, 3)


In [4]:
# Ojo, no es lo mismo un vector unidimensional, que una matriz columna o matriz fila
uni_dimensional = np.array([1,2,3])
print(uni_dimensional.shape)

matriz_fila = uni_dimensional.reshape(-1, 1)
print(matriz_fila.shape)

matriz_columna = uni_dimensional.reshape(1, -1)
print(matriz_columna.shape)

(3,)
(3, 1)
(1, 3)


## Slicing

Los array se pueden hacer cortes para obtener sub arrays

In [5]:
vector = np.array([1,2,3,4,5,6])
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f"El primer elemento de vector es {vector[0]} y el anteultimo es {vector[-2]}")
print(f"La segunda fila de matriz es {matriz[1,:]}, la primer columna es {matriz[:,0]}")
print(f"y podemos sacar submatrices tal como:")
print(matriz[:2, :2])

El primer elemento de vector es 1 y el anteultimo es 5
La segunda fila de matriz es [4 5 6], la primer columna es [1 4 7]
y podemos sacar submatrices tal como:
[[1 2]
 [4 5]]


In [6]:
# Puedo cambiar elementos
vector = np.array([1,2,3,4,5,6])
print(vector)

[1 2 3 4 5 6]


In [7]:
vector[2] = 200
print(vector)

[  1   2 200   4   5   6]


In [8]:
vector[2:4] = [0, 0]
print(vector)

[1 2 0 0 5 6]


In [9]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
matriz[2, 1] = 900
print(matriz)

[[  1   2   3]
 [  4   5   6]
 [  7 900   9]]


In [11]:
matriz[: , -1] = [0, 0, 0]
print(matriz)

[[  1   2   0]
 [  4   5   0]
 [  7 900   0]]


In [12]:
matriz[1:3 , -3:-1] = [[7, 8], [8, 7]]
print(matriz)

[[1 2 0]
 [7 8 0]
 [8 7 0]]


Con numpy contamos de formas de agregar o quitar elementos. Pero como es un array, en realidad crea una nueva copia

In [13]:
vector = np.array([1, 2, 3, 4])
print(vector)

[1 2 3 4]


In [14]:
vector2 = np.append(vector, 5)
print(vector)
print(vector2)

[1 2 3 4]
[1 2 3 4 5]


In [15]:
vector2 = np.append(vector, [10, 11, 12])
print(vector2)

[ 1  2  3  4 10 11 12]


In [16]:
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [17]:
matriz2 = np.append(matriz, 5)
print(matriz2)

[1 2 3 4 5 6 5]


In [18]:
matriz2 = np.append(matriz, [[6, 7, 8]], axis=0)
print(matriz2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [19]:
matriz2 = np.append(matriz, [[6], [7]], axis=1)
print(matriz2)

[[1 2 3 6]
 [4 5 6 7]]


In [20]:
# Insert
matriz = np.array([[1, 1], [2, 2], [3, 3]])
print(matriz)

[[1 1]
 [2 2]
 [3 3]]


In [21]:
matriz2 = np.insert(matriz, 1, 5)
print(matriz2)

[1 5 1 2 2 3 3]


In [22]:
matriz2 = np.insert(matriz, 2, [[5,6]], axis=0)
print(matriz2)

[[1 1]
 [2 2]
 [5 6]
 [3 3]]


In [23]:
matriz2 = np.insert(matriz, [1], [[5],[6],[7]], axis=1)
print(matriz2)

[[1 5 1]
 [2 6 2]
 [3 7 3]]


In [24]:
# delete
matriz = np.array([[1, 1], [2, 2], [3, 3]])
print(matriz)

[[1 1]
 [2 2]
 [3 3]]


In [25]:
matriz2 = np.delete(matriz, 1, 0)
print(matriz2)

[[1 1]
 [3 3]]


In [26]:
matriz2 = np.delete(matriz, 0, None)
print(matriz2)

[1 2 2 3 3]


In [27]:
matriz2 = np.delete(matriz, [0, 2], None)
print(matriz2)

[1 2 3 3]


# Tipos

La forma de que Numpy es muy eficiente en sus cálculos es que obliga a que los datos de los Array sean del mismo tipo, o sea, implementa un Array tradicional.

El atributo dtype nos permite ver que tipo de variable esta conformado el array

In [28]:
ejemplo1 = np.array([1, 2, 3])
print(f"El ejemplo 1 es del tipo {ejemplo1.dtype}")

ejemplo2 = np.array([1, 2., 3])
print(f"El ejemplo 2 es del tipo {ejemplo2.dtype}")

ejemplo3 = np.array([1, 2, "casa"])
print(f"El ejemplo 3 es del tipo {ejemplo3.dtype}")
print(ejemplo3[0] + ejemplo3[1])

El ejemplo 1 es del tipo int64
El ejemplo 2 es del tipo float64
El ejemplo 3 es del tipo <U21
12


In [29]:
# Puedo forzar el tipo
ejemplo4 = np.array([1, 2, 3], dtype=float)
print(f"El ejemplo 4 es del tipo {ejemplo4.dtype}")

El ejemplo 4 es del tipo float64


In [30]:
# Tambien puedo convertir de tipo
ejemplo5 = ejemplo1.astype(float)
print(f"El ejemplo 1 es del tipo {ejemplo1.dtype}")
print(f"El ejemplo 5 es del tipo {ejemplo5.dtype}")

El ejemplo 1 es del tipo int64
El ejemplo 5 es del tipo float64


## Unos y ceros

NumPy tiene métodos incorporados que permiten crear arreglos de unos o ceros.

In [31]:
ceros = np.zeros(4)
print(ceros)

unos = np.ones(5)
print(unos)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## Otros metodos que permiten crear array de valores

In [32]:
rango_valores = np.arange(10)
print(rango_valores)

rango_valores = np.arange(-10, 10, 2)
print(rango_valores)

[0 1 2 3 4 5 6 7 8 9]
[-10  -8  -6  -4  -2   0   2   4   6   8]


In [33]:
rango_lineas = np.linspace(0, 10, 11)
print(rango_lineas)

rango_lineas = np.linspace(0, 5, 11)
print(rango_lineas)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [34]:
#Podemos crear matrices identidad
identidad_2 = np.eye(2)
print(identidad_2)

identidad_4 = np.eye(4)
print(identidad_4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
aleatorio = np.random.randint(0, 10, 10)
print(aleatorio)

aleatorio = np.random.rand(3, 2)
print(aleatorio)

[9 5 7 4 9 1 5 1 9 8]
[[0.96390656 0.16298081]
 [0.9331148  0.74140766]
 [0.9013677  0.30172954]]


## Axis en Numpy

En array de dos dimensiones, los axes son las direcciones a travez de las filas y columnas

In [36]:
# Veamos con np.sum() las diferencias

matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [37]:
#Sumamos en direccion de las filas
np.sum(matriz, axis=0)

array([5, 7, 9])

In [38]:
#Sumamos en direccion de las columnas
np.sum(matriz, axis=1)

array([ 6, 15])

In [39]:
#Sumamos todos los elementos
np.sum(matriz)

21

In [40]:
#Esto es equivalente a hacer
np.sum(np.sum(matriz, axis=1), axis=0)

21

In [41]:
#Ahora np.concatenate()

a = np.array([[1, 1], [1, 1]])
b = np.array([[5, 5], [5, 5]])
print(a)
print(b)

[[1 1]
 [1 1]]
[[5 5]
 [5 5]]


In [42]:
#Concatenamos en direccion de las filas
np.concatenate([a,b], axis=0)

array([[1, 1],
       [1, 1],
       [5, 5],
       [5, 5]])

In [43]:
#Concatenamos en direccion de las columnas
np.concatenate([a,b], axis=1)

array([[1, 1, 5, 5],
       [1, 1, 5, 5]])

In [44]:
# Por ultimo, los array unidimensionales, tienen un solo eje
vector_1 = np.array([1,1,1])
vector_9 = np.array([9,9,9])

In [45]:
# np.sum()
np.sum(vector_1, axis=0)

3

In [46]:
np.sum(vector_1, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [47]:
np.concatenate([vector_1, vector_9], axis=0)

array([1, 1, 1, 9, 9, 9])

Aca tenemos una fuente de confusion ya que si fuera un array de dos dimensiones, si axis=0, se acomodaria uno abajo del otro, pero como es de una sola dimension, es en realidad uno al lado del otro. El eje en una array de una sola dimension **no** apunta hacia abajo.

Se recomienda evitar usar *axis* en array unidimensionales

Ahora si trabajamos con matrices filas, el panomara es diferente:

In [48]:
# Estos son array de dos dimensiones
arr_1 = np.array([1,1,1]).reshape([1, -1])
arr_9 = np.array([9,9,9]).reshape([1, -1])

In [49]:
np.concatenate([arr_1, arr_9], axis=0)

array([[1, 1, 1],
       [9, 9, 9]])

In [50]:
np.concatenate([arr_1, arr_9], axis=1)

array([[1, 1, 1, 9, 9, 9]])

# Leyendo datos

Con numpy podemos leer CSV para levantar arrays


In [51]:
arr = np.loadtxt("./datasets/example.csv",
                 delimiter=",")

In [52]:
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2.

In [53]:
arr.shape

(11, 35)

In [54]:
arr.dtype

dtype('float64')

In [55]:
arr.sum()

630.0

## Reshape

Con Reshape podemos convertir array de una dimension a otra. Esta funcion es muy util

In [56]:
vector_unidimensional = np.array([0, 1, 2, 3, 4, 5])

In [57]:
# Lo transformemos en un vector columna
vector_unidimensional.reshape([-1, 1])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
# Ahora en una matriz
vector_unidimensional.reshape([2, -1])

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
# O en esta otra matriz
vector_unidimensional.reshape([-1, 2])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
# Probemos una de tres dimensiones
vector_unidimensional.reshape([-1, 1, 2])

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [61]:
# Tambien podemos "aplanar" matrices en un array de una dimension
a = np.array([[1, 1], [2, 2]])

print(a)

[[1 1]
 [2 2]]


In [62]:
a.reshape(-1)

array([1, 1, 2, 2])

# Operaciones

Por último, nos queda un millar de tipos de diferentes de operaciones en Numpy

In [63]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


In [64]:
#Suma
a + b

array([[11, 13, 15],
       [17, 19, 21]])

In [65]:
#Restar
a - b

array([[-9, -9, -9],
       [-9, -9, -9]])

In [66]:
#Multiplo de un array por un escalar
2*a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [67]:
#Operaciones algebraicas de matrices o vectores
a + 2*b

array([[21, 24, 27],
       [30, 33, 36]])

In [68]:
#Multiplicar elemento a elemento (esto no es una matriz, sino es el producto de dos array)
a * b

array([[10, 22, 36],
       [52, 70, 90]])

In [69]:
#Elevar al cuadrado elemento a elemento (esto no es una matriz)
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [70]:
#Dividir elemento a elemento (esto no es una matriz)
a / b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [71]:
#Multiplicar dos matrices
a = np.array([[1,2,3],
              [4,5,6]])

c = np.array([[10,11],
              [13,14],
              [12,15]])

np.matmul(a,c)

array([[ 72,  84],
       [177, 204]])

In [72]:
np.matmul(c,a)

array([[ 54,  75,  96],
       [ 69,  96, 123],
       [ 72,  99, 126]])

In [73]:
#Transponer una matriz
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
# Recordar que para multiplicar matrices las columnas de la primera matriz tienen que ser igual a las filas de la segunda
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [75]:
np.matmul(a,b.T)

array([[ 68,  86],
       [167, 212]])

In [76]:
#Trigonometria

angles = np.array([np.pi, np.pi/2, np.pi/4, 0])

In [77]:
np.cos(angles)

array([-1.00000000e+00,  6.12323400e-17,  7.07106781e-01,  1.00000000e+00])

In [78]:
np.sin(angles)

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 0.00000000e+00])

In [79]:
np.tan(angles)

array([-1.22464680e-16,  1.63312394e+16,  1.00000000e+00,  0.00000000e+00])

In [80]:
cos_values = np.cos(angles)
np.arccos(cos_values)

array([3.14159265, 1.57079633, 0.78539816, 0.        ])